# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push: {}
  pull_request_target: {}
env:
  BUILD_NUMBER: 'UNOFFICIAL-${{ github.sha }}'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: gradle
      - name: Build with Gradle
        run: |
         chmod +x gradlew
         ./gradlew build
         rm -rf DiscordGradleBot
      - uses: actions/checkout@v2
        with:
          repository: ForgeEssentials/DiscordGradleBot
          path: DiscordGradleBot
      - name: Publish Binaries to Discord
        working-directory: DiscordGradleBot
        env:
          DISCORD_TOKEN: '${{ secrets.DISCORD_TOKEN }}'
          CHANNEL_ID: '${{ secrets.CHANNEL_ID }}'
        run: |
          chmod +x gradlew
          ./gradlew publishToDiscord
      - uses: actions/upload-artifact@v2
        with:
          name: binaries-${{ github.sha }}
          path: ./build/libs/
      - uses: actions/upload-artifact@v2
        with:
          name: ts-files-${{ github.sha }}
          path: jscripting/*.d.ts
